import type { Requirement } from '../types';

/**
 * Agentic / multi-agent governance — first-class requirement family.
 * These are the controls the Agent Governance screen and the
 * policy/implementation gap engine key off directly.
 */
export const AGENT_GOVERNANCE_REQUIREMENTS: Requirement[] = [
  {
    id: 'REQ-AGENT-IDENTITY-001',
    framework: 'agent-governance',
    reference: 'Agent Governance — Identity',
    title: 'Agent Identity and Authentication',
    domain: 'Identity',
    applicability: 'Systems with autonomous or semi-autonomous agents',
    controlObjective: 'Each agent has a distinct identity, is authenticated, and its actions are authorized against that identity.',
    controlIds: ['agent-identity-auth'],
    expectedEvidence: ['Agent architecture document', 'Agent config (identity/credentials)'],
    technicalExpectations: ['Per-agent service identity', 'Authorization check per action'],
    organizationalExpectations: ['Agent owner named'],
    relatedRequirementIds: ['REQ-SEC-AGENTIC-IDENTITY-001'],
    version: '1.0',
    effectiveDate: '2024-01-01',
    source: 'POLICY//AUDIT Agent Governance Model',
  },
  {
    id: 'REQ-AGENT-PRIV-001',
    framework: 'agent-governance',
    reference: 'Agent Governance — Least Privilege',
    title: 'Agent Least-Privilege Tool and Data Permissions',
    domain: 'Least Privilege',
    applicability: 'Systems with autonomous or semi-autonomous agents',
    controlObjective: 'Agents hold only the tool, data and action permissions strictly required for their task.',
    controlIds: ['agent-least-privilege'],
    expectedEvidence: ['Agent permission manifest / config (tools, access levels)', 'Data access policy'],
    technicalExpectations: ['Scoped permissions per tool', 'No standing write/production access unless justified'],
    organizationalExpectations: ['Permission review owner'],
    relatedRequirementIds: ['REQ-SEC-AGENCY-001'],
    version: '1.0',
    effectiveDate: '2024-01-01',
    source: 'POLICY//AUDIT Agent Governance Model',
  },
  {
    id: 'REQ-AGENT-TOOLGOV-001',
    framework: 'agent-governance',
    reference: 'Agent Governance — Tool Governance',
    title: 'Tool Enumeration and Risk Classification',
    domain: 'Tool Governance',
    applicability: 'Systems with autonomous or semi-autonomous agents',
    controlObjective: 'Tools available to an agent are enumerated, classified by risk, and validate input/output.',
    controlIds: ['agent-tool-governance'],
    expectedEvidence: ['Tool registry', 'Tool risk classification'],
    technicalExpectations: ['Input schema validation', 'Output validation before use', 'Dangerous-tool flagging'],
    organizationalExpectations: ['Tool governance owner'],
    relatedRequirementIds: ['REQ-SEC-OUTPUT-001'],
    version: '1.0',
    effectiveDate: '2024-01-01',
    source: 'POLICY//AUDIT Agent Governance Model',
  },
  {
    id: 'REQ-AGENT-APPROVAL-001',
    framework: 'agent-governance',
    reference: 'Agent Governance — Human Approval',
    title: 'Human Approval Gate for High-Impact Actions',
    domain: 'Human Oversight',
    applicability: 'Systems with autonomous or semi-autonomous agents',
    controlObjective: 'High-impact, irreversible or financial/PII-affecting agent actions require explicit human approval.',
    controlIds: ['agent-human-approval', 'human-oversight'],
    expectedEvidence: ['Human oversight SOP', 'Approval workflow config', 'Approval logs'],
    technicalExpectations: ['Approval gate blocks execution until authorized', 'Approval identity logged'],
    organizationalExpectations: ['Approval authority named'],
    relatedRequirementIds: ['REQ-EUAI-HO-001'],
    version: '1.0',
    effectiveDate: '2024-01-01',
    source: 'POLICY//AUDIT Agent Governance Model',
  },
  {
    id: 'REQ-AGENT-KILL-001',
    framework: 'agent-governance',
    reference: 'Agent Governance — Safe Stop',
    title: 'Agent Kill Switch / Safe-Stop Mechanism',
    domain: 'Human Oversight',
    applicability: 'Systems with autonomous or semi-autonomous agents',
    controlObjective: 'An authorized operator can immediately halt agent execution.',
    controlIds: ['agent-kill-switch'],
    expectedEvidence: ['Kill switch design', 'Safe-stop test report'],
    technicalExpectations: ['Stop signal propagates to all in-flight actions', 'Stop tested, not just designed'],
    organizationalExpectations: ['Operator authorized to invoke stop'],
    relatedRequirementIds: ['REQ-EUAI-HO-001'],
    version: '1.0',
    effectiveDate: '2024-01-01',
    source: 'POLICY//AUDIT Agent Governance Model',
  },
  {
    id: 'REQ-AGENT-LOG-001',
    framework: 'agent-governance',
    reference: 'Agent Governance — Logging',
    title: 'Agent Action and Decision Logging',
    domain: 'Logging & Monitoring',
    applicability: 'Systems with autonomous or semi-autonomous agents',
    controlObjective: 'Prompts, tool calls, outputs, decisions, model/policy versions and operator identity are logged with correlation IDs.',
    controlIds: ['record-keeping-logging'],
    expectedEvidence: ['Logging policy', 'Sample structured logs'],
    technicalExpectations: ['Correlation ID per interaction', 'Model/prompt/policy version stamped on log', 'Immutable/tamper-evident log storage'],
    organizationalExpectations: ['Log review owner'],
    relatedRequirementIds: ['REQ-EUAI-RK-001'],
    version: '1.0',
    effectiveDate: '2024-01-01',
    source: 'POLICY//AUDIT Agent Governance Model',
  },
  {
    id: 'REQ-AGENT-MONITOR-001',
    framework: 'agent-governance',
    reference: 'Agent Governance — Monitoring',
    title: 'Agent Behavior and Drift Monitoring',
    domain: 'Monitoring',
    applicability: 'Systems with autonomous or semi-autonomous agents',
    controlObjective: 'Agent behavior is monitored for drift, anomalies, unsafe actions and policy violations.',
    controlIds: ['post-market-monitoring'],
    expectedEvidence: ['Monitoring dashboard/report', 'Anomaly detection configuration'],
    technicalExpectations: ['Automated anomaly/policy-violation detection', 'Alerting to a human owner'],
    organizationalExpectations: ['Monitoring owner'],
    relatedRequirementIds: ['REQ-EUAI-PMM-001'],
    version: '1.0',
    effectiveDate: '2024-01-01',
    source: 'POLICY//AUDIT Agent Governance Model',
  },
  {
    id: 'REQ-AGENT-INCIDENT-001',
    framework: 'agent-governance',
    reference: 'Agent Governance — Incident Response',
    title: 'Agent Incident Detection and Escalation',
    domain: 'Incident Management',
    applicability: 'Systems with autonomous or semi-autonomous agents',
    controlObjective: 'Unsafe or unauthorized agent actions are detected, escalated, contained and reviewed.',
    controlIds: ['incident-response'],
    expectedEvidence: ['Incident response procedure specific to agent actions', 'Post-incident review record'],
    technicalExpectations: ['Automated detection trigger', 'Defined escalation SLA', 'Containment mechanism (e.g. tied to kill switch)'],
    organizationalExpectations: ['Incident owner'],
    relatedRequirementIds: ['REQ-EUAI-IR-001', 'REQ-AGENT-KILL-001'],
    version: '1.0',
    effectiveDate: '2024-01-01',
    source: 'POLICY//AUDIT Agent Governance Model',
  },
  {
    id: 'REQ-AGENT-CHANGE-001',
    framework: 'agent-governance',
    reference: 'Agent Governance — Change Management',
    title: 'Agent/Model/Prompt/Tool Change Management',
    domain: 'Change Management',
    applicability: 'Systems with autonomous or semi-autonomous agents',
    controlObjective: 'Changes to models, prompts, policies, tools or configuration are approved, tracked and reversible.',
    controlIds: ['change-management'],
    expectedEvidence: ['Change management procedure', 'Change log / approval record'],
    technicalExpectations: ['Version-controlled prompt/config', 'Rollback capability', 'Pre-deployment approval gate'],
    organizationalExpectations: ['Change approval owner'],
    relatedRequirementIds: ['REQ-EUAI-QMS-001'],
    version: '1.0',
    effectiveDate: '2024-01-01',
    source: 'POLICY//AUDIT Agent Governance Model',
  },
  {
    id: 'REQ-AGENT-MEMORY-001',
    framework: 'agent-governance',
    reference: 'Agent Governance — Memory & Retrieval',
    title: 'Agent Memory and Retrieval Data Governance',
    domain: 'Data Governance',
    applicability: 'Systems where agents retain memory or retrieve external content',
    controlObjective: 'Data retained in agent memory or pulled via retrieval is governed for sensitivity, retention and provenance.',
    controlIds: ['data-governance', 'data-leakage-prevention'],
    expectedEvidence: ['Memory/retrieval data policy', 'Retention configuration'],
    technicalExpectations: ['Retention limits enforced', 'Sensitive-data exclusion from memory'],
    organizationalExpectations: ['Data governance owner'],
    relatedRequirementIds: [],
    version: '1.0',
    effectiveDate: '2024-01-01',
    source: 'POLICY//AUDIT Agent Governance Model',
  },
];
