import type { Requirement } from '../types';

/**
 * AI Security control layer — concepts drawn from OWASP Top 10 for LLM
 * Applications, OWASP Agentic AI security guidance, and MITRE ATLAS
 * tactics, normalized into auditable requirements. Not a reproduction of
 * any single source; a synthesis for document-evidence auditing.
 */
export const AI_SECURITY_REQUIREMENTS: Requirement[] = [
  {
    id: 'REQ-SEC-INJECT-001',
    framework: 'ai-security',
    reference: 'OWASP LLM01 — Prompt Injection',
    title: 'Prompt Injection Defense',
    domain: 'AI Security',
    applicability: 'LLM-integrated and agentic systems',
    controlObjective: 'Untrusted input (documents, tool output, retrieved content) cannot override system instructions.',
    controlIds: ['prompt-injection-defense'],
    expectedEvidence: ['Input isolation design doc', 'Injection test results'],
    technicalExpectations: ['Instruction/data channel separation', 'Untrusted-content tagging', 'Output validation before action'],
    organizationalExpectations: ['Security review owner'],
    relatedRequirementIds: [],
    version: '2024',
    effectiveDate: '2024-01-01',
    source: 'OWASP Top 10 for LLM Applications (normalized interpretation)',
  },
  {
    id: 'REQ-SEC-LEAK-001',
    framework: 'ai-security',
    reference: 'OWASP LLM02/LLM06 — Sensitive Information Disclosure',
    title: 'Sensitive Data Leakage Prevention',
    domain: 'AI Security',
    applicability: 'LLM-integrated and agentic systems',
    controlObjective: 'Confidential, personal or regulated data cannot exit through model output, logs or tool calls.',
    controlIds: ['data-leakage-prevention'],
    expectedEvidence: ['Data classification policy', 'Output filtering configuration', 'Log redaction policy'],
    technicalExpectations: ['PII/secret redaction on output and logs', 'Data minimization in prompts/context'],
    organizationalExpectations: ['Data protection owner'],
    relatedRequirementIds: [],
    version: '2024',
    effectiveDate: '2024-01-01',
    source: 'OWASP Top 10 for LLM Applications (normalized interpretation)',
  },
  {
    id: 'REQ-SEC-SUPPLY-001',
    framework: 'ai-security',
    reference: 'OWASP LLM03/LLM05 — Supply Chain & Data/Model Poisoning',
    title: 'AI Supply Chain Security',
    domain: 'AI Security',
    applicability: 'Systems using third-party models, data or plugins',
    controlObjective: 'Model, data and dependency provenance is verified; supply-chain tampering risk is assessed.',
    controlIds: ['model-security', 'supplier-vendor-management'],
    expectedEvidence: ['Model/dataset provenance record', 'Dependency scanning report'],
    technicalExpectations: ['Signed/verified model artifacts', 'Dependency pinning'],
    organizationalExpectations: ['Supply chain security owner'],
    relatedRequirementIds: [],
    version: '2024',
    effectiveDate: '2024-01-01',
    source: 'OWASP Top 10 for LLM Applications (normalized interpretation)',
  },
  {
    id: 'REQ-SEC-OUTPUT-001',
    framework: 'ai-security',
    reference: 'OWASP LLM05 — Improper Output Handling',
    title: 'Output Validation Before Downstream Use',
    domain: 'AI Security',
    applicability: 'Systems where model output triggers actions, code execution or rendering',
    controlObjective: 'Model output is validated/sanitized before being executed, rendered or passed to another system.',
    controlIds: ['agent-tool-governance', 'model-security'],
    expectedEvidence: ['Output validation design', 'Sanitization test results'],
    technicalExpectations: ['Schema/allow-list validation on tool-triggering output'],
    organizationalExpectations: [],
    relatedRequirementIds: [],
    version: '2024',
    effectiveDate: '2024-01-01',
    source: 'OWASP Top 10 for LLM Applications (normalized interpretation)',
  },
  {
    id: 'REQ-SEC-AGENCY-001',
    framework: 'ai-security',
    reference: 'OWASP LLM08 — Excessive Agency',
    title: 'Bounded Agent Autonomy',
    domain: 'AI Security',
    applicability: 'Agentic and tool-using AI systems',
    controlObjective: 'Agents are granted the minimum autonomy and permissions required, with explicit boundaries.',
    controlIds: ['agent-least-privilege', 'agent-tool-governance'],
    expectedEvidence: ['Agent permission manifest', 'Tool allow-list'],
    technicalExpectations: ['Scoped tool permissions', 'Action allow-list enforcement'],
    organizationalExpectations: ['Agent permission owner'],
    relatedRequirementIds: [],
    version: '2024',
    effectiveDate: '2024-01-01',
    source: 'OWASP Top 10 for LLM Applications (normalized interpretation)',
  },
  {
    id: 'REQ-SEC-ADV-001',
    framework: 'ai-security',
    reference: 'MITRE ATLAS — Adversarial ML Evasion',
    title: 'Adversarial Robustness Testing',
    domain: 'AI Security',
    applicability: 'Models exposed to untrusted or adversarial input',
    controlObjective: 'The model is tested against adversarial manipulation attempts relevant to its exposure.',
    controlIds: ['accuracy-robustness', 'cybersecurity'],
    expectedEvidence: ['Adversarial test report', 'Red-team findings'],
    technicalExpectations: ['Defined adversarial test scenarios'],
    organizationalExpectations: ['Red-team/security test owner'],
    relatedRequirementIds: ['REQ-EUAI-AR-001'],
    version: '2024',
    effectiveDate: '2024-01-01',
    source: 'MITRE ATLAS (normalized interpretation)',
  },
  {
    id: 'REQ-SEC-APIABUSE-001',
    framework: 'ai-security',
    reference: 'OWASP LLM10 — Unbounded Consumption',
    title: 'Model/API Abuse and Rate-Limit Controls',
    domain: 'AI Security',
    applicability: 'Systems exposing a model or agent via API',
    controlObjective: 'Model/API access is rate-limited and monitored for abusive or extraction-oriented usage.',
    controlIds: ['model-security'],
    expectedEvidence: ['Rate limiting configuration', 'Abuse monitoring record'],
    technicalExpectations: ['Rate limit / quota enforcement', 'Anomalous-usage alerting'],
    organizationalExpectations: [],
    relatedRequirementIds: [],
    version: '2024',
    effectiveDate: '2024-01-01',
    source: 'OWASP Top 10 for LLM Applications (normalized interpretation)',
  },
  {
    id: 'REQ-SEC-AGENTIC-IDENTITY-001',
    framework: 'ai-security',
    reference: 'OWASP Agentic Security — Agent Identity',
    title: 'Distinct Agent Identity and Authorization',
    domain: 'Agentic Security',
    applicability: 'Multi-agent and autonomous systems',
    controlObjective: 'Each agent/service has a distinct authenticated identity used to authorize its actions.',
    controlIds: ['agent-identity-auth'],
    expectedEvidence: ['Agent identity/credential design', 'Authorization matrix'],
    technicalExpectations: ['Per-agent credentials', 'Authorization check before privileged action'],
    organizationalExpectations: [],
    relatedRequirementIds: [],
    version: '2024',
    effectiveDate: '2024-01-01',
    source: 'OWASP Agentic AI Security Guidance (normalized interpretation)',
  },
  {
    id: 'REQ-SEC-AGENTIC-COMMS-001',
    framework: 'ai-security',
    reference: 'OWASP Agentic Security — Inter-Agent Communication',
    title: 'Secure Inter-Agent Communication',
    domain: 'Agentic Security',
    applicability: 'Multi-agent systems',
    controlObjective: 'Messages between agents are authenticated and cannot be spoofed or replayed to trigger unintended action.',
    controlIds: ['agent-identity-auth', 'agent-tool-governance'],
    expectedEvidence: ['Inter-agent protocol design', 'Message authentication mechanism'],
    technicalExpectations: ['Signed/authenticated inter-agent messages'],
    organizationalExpectations: [],
    relatedRequirementIds: [],
    version: '2024',
    effectiveDate: '2024-01-01',
    source: 'OWASP Agentic AI Security Guidance (normalized interpretation)',
  },
];
