import type { Requirement } from '../types';

/**
 * EU AI Act — normalized, paraphrased requirement seed set.
 *
 * This is NOT a reproduction of the Regulation's legal text, and it is not
 * an exhaustive Article-by-Article encoding. It is a curated, engineering-
 * oriented translation of the obligations that show up most often in real
 * governance documentation, structured so each one can be evaluated against
 * evidence. Article references are informational pointers for a human
 * reviewer to verify against the source text, not a substitute for it.
 *
 * POLICY//AUDIT does not provide legal advice and does not determine legal
 * compliance. See README "Limitations".
 */
export const EU_AI_ACT_REQUIREMENTS: Requirement[] = [
  {
    id: 'REQ-EUAI-RM-001',
    framework: 'eu-ai-act',
    reference: 'Art. 9',
    title: 'Risk Management System',
    domain: 'Risk Management',
    applicability: 'High-risk AI systems',
    controlObjective: 'Maintain a continuous, iterative risk management process across the AI system lifecycle.',
    controlIds: ['risk-management'],
    expectedEvidence: ['AI risk assessment', 'Risk register', 'Residual risk evaluation'],
    technicalExpectations: ['Documented risk identification method', 'Risk treatment tracking', 'Periodic re-assessment cadence'],
    organizationalExpectations: ['Named risk owner', 'Review cycle defined'],
    relatedRequirementIds: ['REQ-ISO23894-RM-001', 'REQ-NIST-MAP-002'],
    version: '2024',
    effectiveDate: '2024-08-01',
    source: 'EU AI Act (Regulation (EU) 2024/1689)',
  },
  {
    id: 'REQ-EUAI-DG-001',
    framework: 'eu-ai-act',
    reference: 'Art. 10',
    title: 'Data and Data Governance',
    domain: 'Data Governance',
    applicability: 'High-risk AI systems',
    controlObjective: 'Training, validation and testing data meet quality criteria and bias examination.',
    controlIds: ['data-governance'],
    expectedEvidence: ['Data governance policy', 'Dataset documentation', 'Bias/quality examination record'],
    technicalExpectations: ['Data lineage tracking', 'Bias testing procedure', 'Data quality checks'],
    organizationalExpectations: ['Data governance owner'],
    relatedRequirementIds: ['REQ-ISO42001-DATA-001'],
    version: '2024',
    effectiveDate: '2024-08-01',
    source: 'EU AI Act (Regulation (EU) 2024/1689)',
  },
  {
    id: 'REQ-EUAI-TD-001',
    framework: 'eu-ai-act',
    reference: 'Art. 11',
    title: 'Technical Documentation',
    domain: 'Technical Documentation',
    applicability: 'High-risk AI systems',
    controlObjective: 'Technical documentation exists before market placement and is kept up to date.',
    controlIds: ['technical-documentation'],
    expectedEvidence: ['System architecture document', 'Model card', 'Intended purpose statement'],
    technicalExpectations: ['Architecture diagram', 'Performance metrics', 'Known limitations section'],
    organizationalExpectations: ['Document owner', 'Version control'],
    relatedRequirementIds: ['REQ-ISO42001-DOC-001'],
    version: '2024',
    effectiveDate: '2024-08-01',
    source: 'EU AI Act (Regulation (EU) 2024/1689)',
  },
  {
    id: 'REQ-EUAI-RK-001',
    framework: 'eu-ai-act',
    reference: 'Art. 12',
    title: 'Record-Keeping / Automatic Logging',
    domain: 'Logging & Monitoring',
    applicability: 'High-risk AI systems',
    controlObjective: 'The system automatically logs events relevant to identifying risks and substantial modifications.',
    controlIds: ['record-keeping-logging'],
    expectedEvidence: ['Logging policy', 'Log retention configuration', 'Sample logs'],
    technicalExpectations: ['Timestamped event logs', 'Decision/output logging', 'Log integrity protection'],
    organizationalExpectations: ['Log review responsibility'],
    relatedRequirementIds: ['REQ-AGENT-LOG-001', 'REQ-NIST-MANAGE-002'],
    version: '2024',
    effectiveDate: '2024-08-01',
    source: 'EU AI Act (Regulation (EU) 2024/1689)',
  },
  {
    id: 'REQ-EUAI-TR-001',
    framework: 'eu-ai-act',
    reference: 'Art. 13 / Art. 50',
    title: 'Transparency and Provision of Information to Users',
    domain: 'Transparency',
    applicability: 'High-risk AI systems; certain AI systems interacting with natural persons',
    controlObjective: 'Deployers/users are given clear information on the system, its purpose and limitations.',
    controlIds: ['transparency'],
    expectedEvidence: ['User-facing disclosure', 'Instructions for use', 'AI-interaction notice'],
    technicalExpectations: ['Disclosure surfaced at point of interaction', 'Capability/limitation statement'],
    organizationalExpectations: ['Disclosure content owner'],
    relatedRequirementIds: [],
    version: '2024',
    effectiveDate: '2024-08-01',
    source: 'EU AI Act (Regulation (EU) 2024/1689)',
  },
  {
    id: 'REQ-EUAI-HO-001',
    framework: 'eu-ai-act',
    reference: 'Art. 14',
    title: 'Human Oversight',
    domain: 'Human Oversight',
    applicability: 'High-risk AI systems',
    controlObjective: 'Natural persons can effectively oversee the system, including understanding, monitoring and intervening.',
    controlIds: ['human-oversight'],
    expectedEvidence: ['Human oversight procedure', 'Override mechanism description', 'Escalation procedure'],
    technicalExpectations: ['Override/stop capability', 'Operator authorization gate', 'Audit trail of interventions'],
    organizationalExpectations: ['Named oversight role', 'Operator training record'],
    relatedRequirementIds: ['REQ-AGENT-APPROVAL-001', 'REQ-AGENT-KILL-001', 'REQ-ISO42001-HO-001'],
    version: '2024',
    effectiveDate: '2024-08-01',
    source: 'EU AI Act (Regulation (EU) 2024/1689)',
  },
  {
    id: 'REQ-EUAI-AR-001',
    framework: 'eu-ai-act',
    reference: 'Art. 15',
    title: 'Accuracy, Robustness and Cybersecurity',
    domain: 'Accuracy & Robustness',
    applicability: 'High-risk AI systems',
    controlObjective: 'The system achieves an appropriate accuracy level and is resilient to errors, faults and attacks.',
    controlIds: ['accuracy-robustness', 'cybersecurity'],
    expectedEvidence: ['Accuracy test report', 'Robustness test report', 'Security test report'],
    technicalExpectations: ['Defined accuracy metric and threshold', 'Adversarial/robustness testing', 'Fallback/degradation behavior'],
    organizationalExpectations: ['Test sign-off owner'],
    relatedRequirementIds: ['REQ-SEC-ADV-001'],
    version: '2024',
    effectiveDate: '2024-08-01',
    source: 'EU AI Act (Regulation (EU) 2024/1689)',
  },
  {
    id: 'REQ-EUAI-QMS-001',
    framework: 'eu-ai-act',
    reference: 'Art. 17',
    title: 'Quality Management System',
    domain: 'Quality Management',
    applicability: 'Providers of high-risk AI systems',
    controlObjective: 'A documented QMS governs design, development, testing, deployment and change.',
    controlIds: ['quality-management', 'change-management'],
    expectedEvidence: ['QMS documentation', 'Change management procedure'],
    technicalExpectations: ['Version-controlled change records', 'Approval workflow evidence'],
    organizationalExpectations: ['QMS owner', 'Change approval board or role'],
    relatedRequirementIds: ['REQ-AGENT-CHANGE-001'],
    version: '2024',
    effectiveDate: '2024-08-01',
    source: 'EU AI Act (Regulation (EU) 2024/1689)',
  },
  {
    id: 'REQ-EUAI-PMM-001',
    framework: 'eu-ai-act',
    reference: 'Art. 72',
    title: 'Post-Market Monitoring',
    domain: 'Monitoring',
    applicability: 'Providers of high-risk AI systems',
    controlObjective: 'Performance and risk of the deployed system are actively monitored after release.',
    controlIds: ['post-market-monitoring'],
    expectedEvidence: ['Post-market monitoring plan', 'Monitoring dashboards or reports'],
    technicalExpectations: ['Drift/performance monitoring', 'Feedback loop from operations to risk register'],
    organizationalExpectations: ['Monitoring owner'],
    relatedRequirementIds: ['REQ-AGENT-MONITOR-001'],
    version: '2024',
    effectiveDate: '2024-08-01',
    source: 'EU AI Act (Regulation (EU) 2024/1689)',
  },
  {
    id: 'REQ-EUAI-IR-001',
    framework: 'eu-ai-act',
    reference: 'Art. 73',
    title: 'Serious Incident Reporting',
    domain: 'Incident Management',
    applicability: 'Providers of high-risk AI systems',
    controlObjective: 'Serious incidents and malfunctions are detected, investigated and reported within required timelines.',
    controlIds: ['incident-response'],
    expectedEvidence: ['Incident response procedure', 'Incident log', 'Escalation SLA'],
    technicalExpectations: ['Detection mechanism', 'Escalation trigger definition', 'Root-cause/post-incident review'],
    organizationalExpectations: ['Incident response owner', 'Regulatory reporting responsibility'],
    relatedRequirementIds: ['REQ-AGENT-INCIDENT-001'],
    version: '2024',
    effectiveDate: '2024-08-01',
    source: 'EU AI Act (Regulation (EU) 2024/1689)',
  },
  {
    id: 'REQ-EUAI-DEP-001',
    framework: 'eu-ai-act',
    reference: 'Art. 26',
    title: 'Deployer Obligations',
    domain: 'Accountability',
    applicability: 'Deployers of high-risk AI systems',
    controlObjective: 'Deployers use the system per instructions, assign human oversight and monitor operation.',
    controlIds: ['accountability-ownership', 'human-oversight'],
    expectedEvidence: ['Deployer operating procedure', 'Named oversight personnel'],
    technicalExpectations: ['Operational usage logging'],
    organizationalExpectations: ['Deployer oversight role assigned'],
    relatedRequirementIds: ['REQ-EUAI-HO-001'],
    version: '2024',
    effectiveDate: '2024-08-01',
    source: 'EU AI Act (Regulation (EU) 2024/1689)',
  },
  {
    id: 'REQ-EUAI-LIT-001',
    framework: 'eu-ai-act',
    reference: 'Art. 4',
    title: 'AI Literacy',
    domain: 'Training',
    applicability: 'Providers and deployers',
    controlObjective: 'Staff involved with the AI system have sufficient AI literacy for their role.',
    controlIds: ['ai-literacy-training'],
    expectedEvidence: ['Training program record', 'Role-based competency requirement'],
    technicalExpectations: [],
    organizationalExpectations: ['Training owner', 'Completion tracking'],
    relatedRequirementIds: [],
    version: '2024',
    effectiveDate: '2025-02-02',
    source: 'EU AI Act (Regulation (EU) 2024/1689)',
  },
  {
    id: 'REQ-EUAI-PROHIB-001',
    framework: 'eu-ai-act',
    reference: 'Art. 5',
    title: 'Prohibited AI Practices',
    domain: 'Prohibited Practices',
    applicability: 'All AI systems',
    controlObjective: 'The system does not perform practices prohibited outright (e.g. manipulative techniques causing harm, certain biometric categorization/inference, social scoring).',
    controlIds: ['risk-management', 'accountability-ownership'],
    expectedEvidence: ['Prohibited-use screening record', 'Use-case review sign-off'],
    technicalExpectations: ['Use-case boundary enforced in design'],
    organizationalExpectations: ['Legal/compliance sign-off owner'],
    relatedRequirementIds: [],
    version: '2024',
    effectiveDate: '2025-02-02',
    source: 'EU AI Act (Regulation (EU) 2024/1689)',
  },
  {
    id: 'REQ-EUAI-GPAI-001',
    framework: 'eu-ai-act',
    reference: 'Art. 53',
    title: 'GPAI Model Documentation',
    domain: 'GPAI',
    applicability: 'Providers of general-purpose AI models',
    controlObjective: 'Technical documentation and downstream-usable information is maintained for the GPAI model.',
    controlIds: ['technical-documentation', 'transparency'],
    expectedEvidence: ['Model documentation', 'Training data summary', 'Downstream integration guide'],
    technicalExpectations: ['Capability/limitation disclosure', 'Copyright policy reference'],
    organizationalExpectations: ['GPAI documentation owner'],
    relatedRequirementIds: [],
    version: '2024',
    effectiveDate: '2025-08-02',
    source: 'EU AI Act (Regulation (EU) 2024/1689)',
  },
  {
    id: 'REQ-EUAI-CONF-001',
    framework: 'eu-ai-act',
    reference: 'Art. 43',
    title: 'Conformity Assessment',
    domain: 'Conformity',
    applicability: 'High-risk AI systems',
    controlObjective: 'The system undergoes a conformity assessment procedure before/at market placement.',
    controlIds: ['quality-management', 'accountability-ownership'],
    expectedEvidence: ['Conformity assessment record', 'CE marking/declaration of conformity'],
    technicalExpectations: [],
    organizationalExpectations: ['Conformity assessment owner'],
    relatedRequirementIds: [],
    version: '2024',
    effectiveDate: '2026-08-02',
    source: 'EU AI Act (Regulation (EU) 2024/1689)',
  },
];
