import type { Requirement } from '../types';

/**
 * ISO/IEC 23894 (AI Risk Management guidance) — normalized interpretation,
 * not a reproduction of the guidance text.
 */
export const ISO_23894_REQUIREMENTS: Requirement[] = [
  {
    id: 'REQ-ISO23894-CTX-001',
    framework: 'iso-23894',
    reference: 'Clause 5 (Context)',
    title: 'Establish Risk Management Context',
    domain: 'Risk Management',
    applicability: 'Organizations managing AI risk',
    controlObjective: 'Internal/external context, stakeholders and risk criteria are established before assessment.',
    controlIds: ['risk-management'],
    expectedEvidence: ['Risk context statement', 'Stakeholder register'],
    technicalExpectations: [],
    organizationalExpectations: ['Context owner'],
    relatedRequirementIds: [],
    version: '2023',
    effectiveDate: '2023-02-01',
    source: 'ISO/IEC 23894:2023 (normalized interpretation)',
  },
  {
    id: 'REQ-ISO23894-RM-001',
    framework: 'iso-23894',
    reference: 'Clause 6.2 (Risk Identification)',
    title: 'AI Risk Identification',
    domain: 'Risk Management',
    applicability: 'Organizations managing AI risk',
    controlObjective: 'AI-specific risk sources (data, model, use, societal) are systematically identified.',
    controlIds: ['risk-management'],
    expectedEvidence: ['Risk identification worksheet', 'Risk taxonomy'],
    technicalExpectations: [],
    organizationalExpectations: ['Risk identification owner'],
    relatedRequirementIds: ['REQ-EUAI-RM-001'],
    version: '2023',
    effectiveDate: '2023-02-01',
    source: 'ISO/IEC 23894:2023 (normalized interpretation)',
  },
  {
    id: 'REQ-ISO23894-AN-001',
    framework: 'iso-23894',
    reference: 'Clause 6.3 (Risk Analysis)',
    title: 'AI Risk Analysis',
    domain: 'Risk Management',
    applicability: 'Organizations managing AI risk',
    controlObjective: 'Identified risks are analyzed for likelihood and consequence.',
    controlIds: ['risk-management'],
    expectedEvidence: ['Risk analysis record', 'Likelihood/impact scoring'],
    technicalExpectations: [],
    organizationalExpectations: [],
    relatedRequirementIds: [],
    version: '2023',
    effectiveDate: '2023-02-01',
    source: 'ISO/IEC 23894:2023 (normalized interpretation)',
  },
  {
    id: 'REQ-ISO23894-EV-001',
    framework: 'iso-23894',
    reference: 'Clause 6.4 (Risk Evaluation)',
    title: 'AI Risk Evaluation',
    domain: 'Risk Management',
    applicability: 'Organizations managing AI risk',
    controlObjective: 'Analyzed risks are compared against risk criteria to decide treatment priority.',
    controlIds: ['risk-management'],
    expectedEvidence: ['Risk evaluation record', 'Risk acceptance criteria'],
    technicalExpectations: [],
    organizationalExpectations: ['Risk acceptance authority'],
    relatedRequirementIds: [],
    version: '2023',
    effectiveDate: '2023-02-01',
    source: 'ISO/IEC 23894:2023 (normalized interpretation)',
  },
  {
    id: 'REQ-ISO23894-TR-001',
    framework: 'iso-23894',
    reference: 'Clause 6.5 (Risk Treatment)',
    title: 'AI Risk Treatment',
    domain: 'Risk Management',
    applicability: 'Organizations managing AI risk',
    controlObjective: 'Selected treatments (mitigate, transfer, avoid, accept) are implemented and tracked.',
    controlIds: ['risk-management', 'change-management'],
    expectedEvidence: ['Risk treatment plan', 'Treatment status tracking'],
    technicalExpectations: ['Control implementation evidence'],
    organizationalExpectations: ['Treatment owner'],
    relatedRequirementIds: [],
    version: '2023',
    effectiveDate: '2023-02-01',
    source: 'ISO/IEC 23894:2023 (normalized interpretation)',
  },
  {
    id: 'REQ-ISO23894-MON-001',
    framework: 'iso-23894',
    reference: 'Clause 7 (Monitoring and Review)',
    title: 'Risk Monitoring and Review',
    domain: 'Monitoring',
    applicability: 'Organizations managing AI risk',
    controlObjective: 'Risk levels and treatment effectiveness are monitored and reviewed on a defined cadence.',
    controlIds: ['post-market-monitoring', 'risk-management'],
    expectedEvidence: ['Risk review log', 'Monitoring cadence definition'],
    technicalExpectations: ['Monitoring mechanism/tooling'],
    organizationalExpectations: ['Review owner'],
    relatedRequirementIds: ['REQ-EUAI-PMM-001'],
    version: '2023',
    effectiveDate: '2023-02-01',
    source: 'ISO/IEC 23894:2023 (normalized interpretation)',
  },
  {
    id: 'REQ-ISO23894-COMM-001',
    framework: 'iso-23894',
    reference: 'Clause 8 (Communication and Consultation)',
    title: 'Risk Communication',
    domain: 'Governance',
    applicability: 'Organizations managing AI risk',
    controlObjective: 'Risk information is communicated to relevant internal and external stakeholders.',
    controlIds: ['transparency', 'accountability-ownership'],
    expectedEvidence: ['Risk communication plan', 'Stakeholder reporting record'],
    technicalExpectations: [],
    organizationalExpectations: ['Communication owner'],
    relatedRequirementIds: [],
    version: '2023',
    effectiveDate: '2023-02-01',
    source: 'ISO/IEC 23894:2023 (normalized interpretation)',
  },
  {
    id: 'REQ-ISO23894-LIFE-001',
    framework: 'iso-23894',
    reference: 'Clause 9 (Lifecycle Considerations)',
    title: 'Risk Management Across the AI Lifecycle',
    domain: 'Lifecycle Management',
    applicability: 'Organizations managing AI risk',
    controlObjective: 'Risk management activities recur across design, development, deployment and retirement.',
    controlIds: ['lifecycle-management', 'risk-management'],
    expectedEvidence: ['Lifecycle risk checkpoints'],
    technicalExpectations: [],
    organizationalExpectations: ['Lifecycle risk owner'],
    relatedRequirementIds: [],
    version: '2023',
    effectiveDate: '2023-02-01',
    source: 'ISO/IEC 23894:2023 (normalized interpretation)',
  },
];
