import type { Requirement } from '../types';

/**
 * ISO/IEC 42001 (AI Management System) — normalized control interpretations.
 * These are original paraphrases of the concepts the standard addresses,
 * not reproductions of its clause text (which is copyrighted). Reference
 * strings point to the clause area for a reviewer holding the standard,
 * they are not quotations.
 */
export const ISO_42001_REQUIREMENTS: Requirement[] = [
  {
    id: 'REQ-ISO42001-LEAD-001',
    framework: 'iso-42001',
    reference: 'Clause 5 (Leadership)',
    title: 'AI Policy and Leadership Commitment',
    domain: 'Governance',
    applicability: 'Organizations operating an AI management system',
    controlObjective: 'Top management establishes and commits to a documented AI policy.',
    controlIds: ['accountability-ownership'],
    expectedEvidence: ['AI governance policy', 'Leadership sign-off'],
    technicalExpectations: [],
    organizationalExpectations: ['Executive sponsor named', 'Policy review cadence'],
    relatedRequirementIds: [],
    version: '2023',
    effectiveDate: '2023-12-18',
    source: 'ISO/IEC 42001:2023 (normalized interpretation)',
  },
  {
    id: 'REQ-ISO42001-ROLE-001',
    framework: 'iso-42001',
    reference: 'Clause 5.3',
    title: 'Roles, Responsibilities and Authorities',
    domain: 'Governance',
    applicability: 'Organizations operating an AI management system',
    controlObjective: 'AI-related roles and decision authority are defined and communicated.',
    controlIds: ['accountability-ownership'],
    expectedEvidence: ['RACI or ownership matrix', 'Role descriptions'],
    technicalExpectations: [],
    organizationalExpectations: ['Named accountable owner per control'],
    relatedRequirementIds: [],
    version: '2023',
    effectiveDate: '2023-12-18',
    source: 'ISO/IEC 42001:2023 (normalized interpretation)',
  },
  {
    id: 'REQ-ISO42001-RISK-001',
    framework: 'iso-42001',
    reference: 'Clause 6.1',
    title: 'AI Risk Assessment Process',
    domain: 'Risk Management',
    applicability: 'Organizations operating an AI management system',
    controlObjective: 'Risks and opportunities related to AI systems are identified and assessed.',
    controlIds: ['risk-management'],
    expectedEvidence: ['AI risk assessment methodology', 'Risk treatment plan'],
    technicalExpectations: ['Risk scoring method'],
    organizationalExpectations: ['Risk assessment owner'],
    relatedRequirementIds: ['REQ-EUAI-RM-001', 'REQ-ISO23894-RM-001'],
    version: '2023',
    effectiveDate: '2023-12-18',
    source: 'ISO/IEC 42001:2023 (normalized interpretation)',
  },
  {
    id: 'REQ-ISO42001-IMPACT-001',
    framework: 'iso-42001',
    reference: 'Clause 6.1.4',
    title: 'AI System Impact Assessment',
    domain: 'Risk Management',
    applicability: 'AI systems with potential impact on individuals or groups',
    controlObjective: 'Impact on individuals, groups and society is assessed before/during deployment.',
    controlIds: ['risk-management', 'data-governance'],
    expectedEvidence: ['AI impact assessment / DPIA', 'Affected-party analysis'],
    technicalExpectations: [],
    organizationalExpectations: ['Impact assessment owner'],
    relatedRequirementIds: [],
    version: '2023',
    effectiveDate: '2023-12-18',
    source: 'ISO/IEC 42001:2023 (normalized interpretation)',
  },
  {
    id: 'REQ-ISO42001-LIFE-001',
    framework: 'iso-42001',
    reference: 'Clause 8.2',
    title: 'AI System Lifecycle Controls',
    domain: 'Lifecycle Management',
    applicability: 'Organizations operating an AI management system',
    controlObjective: 'Governance activities are defined for each lifecycle stage from design to retirement.',
    controlIds: ['lifecycle-management'],
    expectedEvidence: ['Lifecycle policy', 'Stage-gate checklist'],
    technicalExpectations: ['Retirement/decommission procedure'],
    organizationalExpectations: ['Lifecycle stage owners'],
    relatedRequirementIds: [],
    version: '2023',
    effectiveDate: '2023-12-18',
    source: 'ISO/IEC 42001:2023 (normalized interpretation)',
  },
  {
    id: 'REQ-ISO42001-DATA-001',
    framework: 'iso-42001',
    reference: 'Clause 8.3 / Annex B.7',
    title: 'Data Management for AI Systems',
    domain: 'Data Governance',
    applicability: 'Organizations operating an AI management system',
    controlObjective: 'Data used by AI systems is managed for quality, provenance and appropriate use.',
    controlIds: ['data-governance'],
    expectedEvidence: ['Data management procedure', 'Data provenance record'],
    technicalExpectations: ['Data lineage tracking'],
    organizationalExpectations: ['Data owner'],
    relatedRequirementIds: ['REQ-EUAI-DG-001'],
    version: '2023',
    effectiveDate: '2023-12-18',
    source: 'ISO/IEC 42001:2023 (normalized interpretation)',
  },
  {
    id: 'REQ-ISO42001-RES-001',
    framework: 'iso-42001',
    reference: 'Clause 7.1',
    title: 'Resources for AI Operation',
    domain: 'Resources',
    applicability: 'Organizations operating an AI management system',
    controlObjective: 'Adequate computational, human and data resources are allocated to operate the AI system safely.',
    controlIds: ['quality-management'],
    expectedEvidence: ['Resource allocation record'],
    technicalExpectations: ['Capacity/scaling plan'],
    organizationalExpectations: ['Resource owner'],
    relatedRequirementIds: [],
    version: '2023',
    effectiveDate: '2023-12-18',
    source: 'ISO/IEC 42001:2023 (normalized interpretation)',
  },
  {
    id: 'REQ-ISO42001-TR-001',
    framework: 'iso-42001',
    reference: 'Annex B.5',
    title: 'Transparency to Stakeholders',
    domain: 'Transparency',
    applicability: 'Organizations operating an AI management system',
    controlObjective: 'Stakeholders are given appropriate information about AI system use and behavior.',
    controlIds: ['transparency'],
    expectedEvidence: ['Stakeholder communication record', 'Disclosure content'],
    technicalExpectations: [],
    organizationalExpectations: ['Disclosure owner'],
    relatedRequirementIds: [],
    version: '2023',
    effectiveDate: '2023-12-18',
    source: 'ISO/IEC 42001:2023 (normalized interpretation)',
  },
  {
    id: 'REQ-ISO42001-HO-001',
    framework: 'iso-42001',
    reference: 'Annex B.6.2.6',
    title: 'Human Oversight of AI Systems',
    domain: 'Human Oversight',
    applicability: 'Organizations operating an AI management system',
    controlObjective: 'Human oversight mechanisms are designed into the AI system and its operating procedures.',
    controlIds: ['human-oversight'],
    expectedEvidence: ['Human oversight procedure', 'Escalation path'],
    technicalExpectations: ['Override/intervention capability'],
    organizationalExpectations: ['Oversight role assigned'],
    relatedRequirementIds: ['REQ-EUAI-HO-001'],
    version: '2023',
    effectiveDate: '2023-12-18',
    source: 'ISO/IEC 42001:2023 (normalized interpretation)',
  },
  {
    id: 'REQ-ISO42001-MON-001',
    framework: 'iso-42001',
    reference: 'Clause 9.1',
    title: 'Monitoring, Measurement and Evaluation',
    domain: 'Monitoring',
    applicability: 'Organizations operating an AI management system',
    controlObjective: 'AI system and management-system performance is monitored against defined criteria.',
    controlIds: ['post-market-monitoring'],
    expectedEvidence: ['Monitoring plan', 'Performance review record'],
    technicalExpectations: ['Monitoring metrics defined'],
    organizationalExpectations: ['Monitoring owner'],
    relatedRequirementIds: [],
    version: '2023',
    effectiveDate: '2023-12-18',
    source: 'ISO/IEC 42001:2023 (normalized interpretation)',
  },
  {
    id: 'REQ-ISO42001-IMP-001',
    framework: 'iso-42001',
    reference: 'Clause 10.2',
    title: 'Continual Improvement',
    domain: 'Continual Improvement',
    applicability: 'Organizations operating an AI management system',
    controlObjective: 'Nonconformities and monitoring findings feed back into corrective action.',
    controlIds: ['change-management', 'quality-management'],
    expectedEvidence: ['Corrective action log', 'Improvement review record'],
    technicalExpectations: [],
    organizationalExpectations: ['Improvement process owner'],
    relatedRequirementIds: [],
    version: '2023',
    effectiveDate: '2023-12-18',
    source: 'ISO/IEC 42001:2023 (normalized interpretation)',
  },
  {
    id: 'REQ-ISO42001-DOC-001',
    framework: 'iso-42001',
    reference: 'Clause 7.5',
    title: 'Documented Information Control',
    domain: 'Documentation',
    applicability: 'Organizations operating an AI management system',
    controlObjective: 'Documented information is created, controlled, versioned and retained appropriately.',
    controlIds: ['technical-documentation'],
    expectedEvidence: ['Document control procedure', 'Version history'],
    technicalExpectations: ['Version control system evidence'],
    organizationalExpectations: ['Document control owner'],
    relatedRequirementIds: ['REQ-EUAI-TD-001'],
    version: '2023',
    effectiveDate: '2023-12-18',
    source: 'ISO/IEC 42001:2023 (normalized interpretation)',
  },
  {
    id: 'REQ-ISO42001-SUP-001',
    framework: 'iso-42001',
    reference: 'Annex B.9',
    title: 'Supplier and Third-Party AI Management',
    domain: 'Supplier Management',
    applicability: 'Organizations using third-party AI components or vendors',
    controlObjective: 'Third-party AI components and vendors are assessed and managed for governance risk.',
    controlIds: ['supplier-vendor-management'],
    expectedEvidence: ['Vendor AI risk assessment', 'Third-party contractual requirement'],
    technicalExpectations: [],
    organizationalExpectations: ['Vendor management owner'],
    relatedRequirementIds: [],
    version: '2023',
    effectiveDate: '2023-12-18',
    source: 'ISO/IEC 42001:2023 (normalized interpretation)',
  },
  {
    id: 'REQ-ISO42001-OPS-001',
    framework: 'iso-42001',
    reference: 'Clause 8.1',
    title: 'Operational Controls',
    domain: 'Operations',
    applicability: 'Organizations operating an AI management system',
    controlObjective: 'Operational processes implement the AI policy in day-to-day system operation.',
    controlIds: ['quality-management', 'change-management'],
    expectedEvidence: ['Operating procedure', 'Change control record'],
    technicalExpectations: [],
    organizationalExpectations: ['Operations owner'],
    relatedRequirementIds: [],
    version: '2023',
    effectiveDate: '2023-12-18',
    source: 'ISO/IEC 42001:2023 (normalized interpretation)',
  },
];
