import type { Requirement } from '../types';

/**
 * NIST AI Risk Management Framework — GOVERN / MAP / MEASURE / MANAGE,
 * normalized into auditable requirements.
 */
export const NIST_AI_RMF_REQUIREMENTS: Requirement[] = [
  {
    id: 'REQ-NIST-GOVERN-001',
    framework: 'nist-ai-rmf',
    reference: 'GOVERN 1',
    title: 'AI Governance Policies and Processes',
    domain: 'Governance',
    applicability: 'Organizations developing or deploying AI',
    controlObjective: 'Policies, processes and accountability structures for AI risk are established and enforced.',
    controlIds: ['accountability-ownership', 'quality-management'],
    expectedEvidence: ['AI governance policy', 'Accountability structure document'],
    technicalExpectations: [],
    organizationalExpectations: ['Governance owner', 'Policy enforcement mechanism'],
    relatedRequirementIds: ['REQ-ISO42001-LEAD-001'],
    version: '1.0',
    effectiveDate: '2023-01-26',
    source: 'NIST AI RMF 1.0 (normalized interpretation)',
  },
  {
    id: 'REQ-NIST-GOVERN-002',
    framework: 'nist-ai-rmf',
    reference: 'GOVERN 3',
    title: 'Workforce Diversity and AI Literacy',
    domain: 'Governance',
    applicability: 'Organizations developing or deploying AI',
    controlObjective: 'Staff involved in AI risk management have diverse perspectives and adequate AI literacy.',
    controlIds: ['ai-literacy-training'],
    expectedEvidence: ['Training record', 'Team composition statement'],
    technicalExpectations: [],
    organizationalExpectations: ['Training owner'],
    relatedRequirementIds: ['REQ-EUAI-LIT-001'],
    version: '1.0',
    effectiveDate: '2023-01-26',
    source: 'NIST AI RMF 1.0 (normalized interpretation)',
  },
  {
    id: 'REQ-NIST-GOVERN-003',
    framework: 'nist-ai-rmf',
    reference: 'GOVERN 4',
    title: 'Third-Party AI Risk Governance',
    domain: 'Governance',
    applicability: 'Organizations using third-party AI components',
    controlObjective: 'Risk from third-party data, models and systems is governed with the same rigor as internal AI.',
    controlIds: ['supplier-vendor-management'],
    expectedEvidence: ['Third-party risk policy', 'Vendor assessment record'],
    technicalExpectations: [],
    organizationalExpectations: ['Vendor governance owner'],
    relatedRequirementIds: ['REQ-ISO42001-SUP-001'],
    version: '1.0',
    effectiveDate: '2023-01-26',
    source: 'NIST AI RMF 1.0 (normalized interpretation)',
  },
  {
    id: 'REQ-NIST-MAP-001',
    framework: 'nist-ai-rmf',
    reference: 'MAP 1',
    title: 'Context Mapping',
    domain: 'Risk Management',
    applicability: 'Organizations developing or deploying AI',
    controlObjective: 'Intended purpose, context of use and impacted stakeholders are mapped before risk analysis.',
    controlIds: ['risk-management', 'technical-documentation'],
    expectedEvidence: ['Use-case/context statement', 'Stakeholder impact map'],
    technicalExpectations: [],
    organizationalExpectations: [],
    relatedRequirementIds: [],
    version: '1.0',
    effectiveDate: '2023-01-26',
    source: 'NIST AI RMF 1.0 (normalized interpretation)',
  },
  {
    id: 'REQ-NIST-MAP-002',
    framework: 'nist-ai-rmf',
    reference: 'MAP 3',
    title: 'Risk and Benefit Mapping',
    domain: 'Risk Management',
    applicability: 'Organizations developing or deploying AI',
    controlObjective: 'Benefits and risks of the AI system for each context of use are mapped and documented.',
    controlIds: ['risk-management'],
    expectedEvidence: ['Risk/benefit analysis document'],
    technicalExpectations: [],
    organizationalExpectations: [],
    relatedRequirementIds: ['REQ-EUAI-RM-001'],
    version: '1.0',
    effectiveDate: '2023-01-26',
    source: 'NIST AI RMF 1.0 (normalized interpretation)',
  },
  {
    id: 'REQ-NIST-MEASURE-001',
    framework: 'nist-ai-rmf',
    reference: 'MEASURE 2',
    title: 'AI System Performance and Trustworthiness Testing',
    domain: 'Testing',
    applicability: 'Organizations developing or deploying AI',
    controlObjective: 'The system is tested for validity, reliability, safety, security and fairness.',
    controlIds: ['accuracy-robustness', 'cybersecurity'],
    expectedEvidence: ['Test report', 'Validation results'],
    technicalExpectations: ['Defined test metrics', 'Adversarial/robustness test coverage'],
    organizationalExpectations: ['Test sign-off owner'],
    relatedRequirementIds: ['REQ-EUAI-AR-001'],
    version: '1.0',
    effectiveDate: '2023-01-26',
    source: 'NIST AI RMF 1.0 (normalized interpretation)',
  },
  {
    id: 'REQ-NIST-MEASURE-002',
    framework: 'nist-ai-rmf',
    reference: 'MEASURE 3',
    title: 'Mechanisms for Tracking Identified Risks',
    domain: 'Monitoring',
    applicability: 'Organizations developing or deploying AI',
    controlObjective: 'Identified risks are tracked over time with defined metrics and thresholds.',
    controlIds: ['post-market-monitoring', 'record-keeping-logging'],
    expectedEvidence: ['Risk tracking dashboard/log'],
    technicalExpectations: ['Metric collection mechanism'],
    organizationalExpectations: [],
    relatedRequirementIds: [],
    version: '1.0',
    effectiveDate: '2023-01-26',
    source: 'NIST AI RMF 1.0 (normalized interpretation)',
  },
  {
    id: 'REQ-NIST-MANAGE-001',
    framework: 'nist-ai-rmf',
    reference: 'MANAGE 2',
    title: 'Risk Response and Prioritization',
    domain: 'Risk Management',
    applicability: 'Organizations developing or deploying AI',
    controlObjective: 'Risk responses are prioritized, planned and resourced based on measured risk.',
    controlIds: ['risk-management', 'change-management'],
    expectedEvidence: ['Risk response plan'],
    technicalExpectations: [],
    organizationalExpectations: ['Response prioritization owner'],
    relatedRequirementIds: [],
    version: '1.0',
    effectiveDate: '2023-01-26',
    source: 'NIST AI RMF 1.0 (normalized interpretation)',
  },
  {
    id: 'REQ-NIST-MANAGE-002',
    framework: 'nist-ai-rmf',
    reference: 'MANAGE 4',
    title: 'Incident Response and Recovery',
    domain: 'Incident Management',
    applicability: 'Organizations developing or deploying AI',
    controlObjective: 'Mechanisms exist to respond to, recover from, and communicate about AI incidents.',
    controlIds: ['incident-response'],
    expectedEvidence: ['Incident response plan', 'Post-incident review record'],
    technicalExpectations: ['Detection and escalation mechanism'],
    organizationalExpectations: ['Incident owner'],
    relatedRequirementIds: ['REQ-EUAI-IR-001'],
    version: '1.0',
    effectiveDate: '2023-01-26',
    source: 'NIST AI RMF 1.0 (normalized interpretation)',
  },
];
